name: Build and Deploy to S3
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn clean package
    - name: Zip the application
      run: |
        mkdir -p deployment
        cp target/*.jar deployment/
        cp -r .ebextensions deployment/ || true  # Copy Elastic Beanstalk config if exists
        cp Procfile deployment/ || true  # Copy Procfile if exists
        cd deployment
        zip -r ../springApplication.zip .
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2 
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1
    - name: Upload to S3
      run: |
        aws s3 cp springApplication.zip s3://elasticapp-bucket/springApplication.zip-${{ github.sha }}.zip
        echo "S3 URL: s3://elasticapp-bucket/springApplication.zip-${{ github.sha }}.zip"

        # Deploy the new application version to the Elastic Beanstalk environment
        aws elasticbeanstalk update-environment \
          --environment-name Todo-application-env \
          --version-label "build-${{ github.run_number }}-${{ github.sha }}"
