name: Build and Push to ECR
on:
  push:
    branches: [ feat/docker ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ECR_REGISTRY: public.ecr.aws/j1n7u2e7  # Replace with your ECR URI
      ECR_REPOSITORY: rosetetteh_labapplication
      IMAGE_TAG: latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR Public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public

      - name: Build Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}  # Replace with your ECR URI
          ECR_REPOSITORY: rosetetteh_labapplication
          IMAGE_TAG: latest
        run: |
          echo "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
  # docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

      - name: Push Docker image
        run: |
      # docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
